version: '3'
services:
  render:
    build: render/
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
      - config
      - discovery-server
  config:
    build: config/
    environment:
      - SPRING_PROFILES_ACTIVE=native
#  frontend:
#    build: frontend/
#    ports:
#      - "5174:5173"
  gateway:
    build: gateway/
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8070:8070"
    depends_on:
      - discovery-server
  discovery-server:
    build: discovery-server/
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql